/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Vismay.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Vismay.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node1.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node2.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node3.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node4.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node5.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node6.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node7.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node8.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node9.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node10.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node11.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node12.geometry} material={materials.x1} />
    </group>
  )
}

useGLTF.preload('/Vismay.glb')
